#!/usr/bin/env python
#
# Copyright (C) 2011  Governo do Estado do Rio Grande do Sul
#
#   Author: Lincoln de Sousa <lincoln@gg.rs.gov.br>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import werkzeug.serving
from socketio import SocketIOServer

from ad.webapp import app
from ad.buzz import sio


@werkzeug.serving.run_with_reloader
def run():
    # FIXME: This flag should be set in a config file.
    app.debug = True

    context = sio.setup()
    server = SocketIOServer(
        ('0.0.0.0', 5000),
        sio.BuzzApp(context, app),
        resource='socket.io')
    server.start()
    sio.publisher(context)


if __name__ == '__main__':
    run()
